# Generated by Django 4.2.26 on 2025-11-26 05:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название книги', max_length=200, verbose_name='Название книги')),
                ('author', models.CharField(help_text='Введите имя автора книги', max_length=100, verbose_name='Автор')),
                ('published_date', models.DateField(help_text='Дата публикации книги', verbose_name='Дата публикации')),
                ('description', models.TextField(help_text='Описание книги', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-published_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название издательства', max_length=200, verbose_name='Название издательства')),
                ('country', models.CharField(help_text='Введите страну, где находится издательство', max_length=100, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название книжного магазина', max_length=200, verbose_name='Название магазина')),
                ('city', models.CharField(help_text='Введите город, где находится магазин', max_length=100, verbose_name='Город')),
                ('books', models.ManyToManyField(blank=True, help_text='Книги, которые продаются в этом магазине', related_name='stores', to='books.book', verbose_name='Книги')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Оценка книги от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(help_text='Текст отзыва о книге', verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания отзыва', verbose_name='Дата создания')),
                ('book', models.ForeignKey(help_text='Книга, на которую оставлен отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(help_text='Издательство, опубликовавшее книгу', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.publisher', verbose_name='Издательство'),
        ),
    ]
