# Generated by Django 4.2.26 on 2025-11-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='stores',
            field=models.ManyToManyField(blank=True, help_text='Магазины, где продаётся книга', related_name='books', to='books.store', verbose_name='Магазины'),
        ),
    ]
