# Generated by Django 4.2.26 on 2025-12-05 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок статьи (максимум 200 символов)', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Текст статьи', verbose_name='Содержание')),
                ('author', models.CharField(help_text='Имя автора статьи (максимум 100 символов)', max_length=100, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания статьи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления статьи', verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=False, help_text='Статья опубликована и доступна для просмотра', verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
    ]
