# Generated by Django 4.2.26 on 2025-11-25 06:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Email адрес пользователя', max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Номер телефона пользователя', max_length=15, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, help_text='Адрес доставки пользователя', max_length=255, verbose_name='Адрес доставки')),
                ('is_active', models.BooleanField(default=False, help_text='Указывает, подтвержден ли email пользователя', verbose_name='Аккаунт активен')),
                ('is_staff', models.BooleanField(default=False, help_text='Указывает, является ли пользователь сотрудником', verbose_name='Сотрудник')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Дата и время регистрации пользователя', verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания корзины', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления корзины', verbose_name='Дата обновления')),
                ('user', models.OneToOneField(help_text='Владелец корзины', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Описание категории (необязательно)', null=True, verbose_name='Описание категории')),
                ('parent', models.ForeignKey(blank=True, help_text='Выберите родительскую категорию для создания вложенной категории', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время оформления заказа', verbose_name='Дата создания заказа')),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('shipping', 'Доставляется'), ('delivered', 'Доставлено')], default='processing', help_text='Текущий статус заказа', max_length=20, verbose_name='Статус заказа')),
                ('user', models.ForeignKey(help_text='Пользователь, оформивший заказ', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название товара', max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(help_text='Подробное описание товара', verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена товара в рублях', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена товара')),
                ('stock', models.IntegerField(default=0, help_text='Количество товара на складе', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество на складе')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение товара', null=True, upload_to='products/', verbose_name='Изображение товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время добавления товара', verbose_name='Дата создания')),
                ('category', models.ForeignKey(blank=True, help_text='Выберите категорию товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'shop_products',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Оценка товара от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(help_text='Текст отзыва о товаре', verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания отзыва', verbose_name='Дата создания')),
                ('product', models.ForeignKey(help_text='Товар, на который оставлен отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='Товар')),
                ('user', models.ForeignKey(help_text='Пользователь, оставивший отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Количество товара в заказе', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('order', models.ForeignKey(help_text='Заказ, к которому относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(help_text='Товар в заказе', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказах',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя отправителя сообщения', max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Email отправителя сообщения', max_length=254, verbose_name='Электронная почта')),
                ('message', models.TextField(help_text='Текст сообщения', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время отправки сообщения', verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, отправивший сообщение (если авторизован)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Количество товара в корзине', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('cart', models.ForeignKey(help_text='Корзина, к которой относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(help_text='Товар в корзине', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзинах',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
