# Generated by Django 4.2.26 on 2025-11-25 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя отправителя сообщения', max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Email отправителя сообщения', max_length=254, verbose_name='Электронная почта')),
                ('message', models.TextField(help_text='Текст сообщения (максимум 500 символов)', max_length=500, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время отправки сообщения', verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, отправивший сообщение (если авторизован)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
    ]
